package com.bashmaqawa.pdf.core

import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.RectF
import com.bashmaqawa.pdf.PdfColors
import com.bashmaqawa.pdf.PdfPageSettings
import com.bashmaqawa.pdf.PdfTypography
import com.bashmaqawa.pdf.models.ReportType
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * PDF Page Renderer
 * مُنشئ صفحات PDF
 * 
 * Handles rendering of common page elements:
 * - Professional headers with company branding
 * - Consistent footers with page numbers
 * - Report metadata and timestamps
 */
class PdfPageRenderer {
    
    private val dateFormatter = SimpleDateFormat("yyyy/MM/dd HH:mm", Locale("ar"))
    private val dateOnlyFormatter = SimpleDateFormat("yyyy/MM/dd", Locale("ar"))
    
    // Paints
    private val titlePaint = PdfTypography.createPageTitlePaint()
    private val subtitlePaint = PdfTypography.createSubtitlePaint()
    private val footerPaint = PdfTypography.createFooterPaint()
    private val linePaint = PdfTypography.createLinePaint()
    private val thickLinePaint = PdfTypography.createThickLinePaint()
    private val labelPaint = PdfTypography.createLabelPaint()
    
    companion object {
        private const val COMPANY_NAME_AR = "بشمقاول"
        private const val COMPANY_NAME_EN = "Bashmaqawal"
        private const val COMPANY_TAGLINE_AR = "نظام إدارة المقاولات"
        private const val COMPANY_TAGLINE_EN = "Contractor Management System"
        private const val FOOTER_TEXT_AR = "تم إنشاء هذا التقرير بواسطة تطبيق بشمقاول"
        private const val FOOTER_TEXT_EN = "Generated by Bashmaqawal Mobile Application"
    }
    
    /**
     * Render page header
     * 
     * @param canvas Canvas to draw on
     * @param reportType Type of report being generated
     * @param periodStart Optional period start date
     * @param periodEnd Optional period end date
     * @param pageNumber Current page number (1-indexed)
     * @param isFirstPage True for first page (full header), false for continuation pages
     * @return Y position after header
     */
    fun renderHeader(
        canvas: Canvas,
        reportType: ReportType,
        periodStart: String? = null,
        periodEnd: String? = null,
        pageNumber: Int = 1,
        isFirstPage: Boolean = true
    ): Float {
        val rightX = PdfPageSettings.contentStartX
        var currentY = PdfPageSettings.MARGIN_TOP + 30f
        
        if (isFirstPage) {
            // Full header for first page
            
            // Company name (Arabic)
            canvas.drawText(COMPANY_NAME_AR, rightX, currentY, titlePaint)
            currentY += 20f
            
            // Company tagline (Arabic)
            canvas.drawText(COMPANY_TAGLINE_AR, rightX, currentY, subtitlePaint)
            currentY += 25f
            
            // Separator line
            canvas.drawLine(
                PdfPageSettings.MARGIN_LEFT,
                currentY,
                rightX,
                currentY,
                thickLinePaint
            )
            currentY += 20f
            
            // Report title
            canvas.drawText(reportType.titleArabic, rightX, currentY, titlePaint.apply {
                textSize = PdfTypography.SIZE_SECTION_HEADER + 4f
            })
            currentY += 25f
            
            // Period (if applicable)
            if (periodStart != null && periodEnd != null) {
                val periodText = "الفترة: من $periodStart إلى $periodEnd"
                canvas.drawText(periodText, rightX, currentY, subtitlePaint)
                currentY += 18f
            }
            
            // Generation timestamp
            val timestamp = "تاريخ الإنشاء: ${dateFormatter.format(Date())}"
            canvas.drawText(timestamp, rightX, currentY, labelPaint)
            currentY += 5f
            
            // Another separator
            canvas.drawLine(
                PdfPageSettings.MARGIN_LEFT,
                currentY + 10f,
                rightX,
                currentY + 10f,
                linePaint
            )
            currentY += 25f
            
        } else {
            // Compact header for continuation pages
            
            // Report title (smaller)
            canvas.drawText(
                "${reportType.titleArabic} (تابع)",
                rightX,
                currentY,
                subtitlePaint.apply { typeface = android.graphics.Typeface.DEFAULT_BOLD }
            )
            currentY += 15f
            
            // Light separator
            canvas.drawLine(
                PdfPageSettings.MARGIN_LEFT,
                currentY,
                rightX,
                currentY,
                linePaint
            )
            currentY += 15f
        }
        
        return currentY
    }
    
    /**
     * Render page footer
     * 
     * @param canvas Canvas to draw on
     * @param currentPage Current page number (1-indexed)
     * @param totalPages Total number of pages
     */
    fun renderFooter(
        canvas: Canvas,
        currentPage: Int,
        totalPages: Int
    ) {
        val centerX = PdfPageSettings.A4_WIDTH / 2f
        val footerY = PdfPageSettings.A4_HEIGHT - PdfPageSettings.MARGIN_BOTTOM
        
        // Separator line above footer
        canvas.drawLine(
            PdfPageSettings.MARGIN_LEFT,
            footerY - 25f,
            PdfPageSettings.contentStartX,
            footerY - 25f,
            linePaint
        )
        
        // Footer text
        canvas.drawText(
            FOOTER_TEXT_AR,
            centerX,
            footerY - 12f,
            footerPaint
        )
        
        // Page number
        val pageText = "صفحة $currentPage من $totalPages"
        canvas.drawText(
            pageText,
            centerX,
            footerY,
            footerPaint
        )
    }
    
    /**
     * Render a section header
     * 
     * @param canvas Canvas to draw on
     * @param title Section title
     * @param currentY Current Y position
     * @return Y position after section header
     */
    fun renderSectionHeader(
        canvas: Canvas,
        title: String,
        currentY: Float
    ): Float {
        val rightX = PdfPageSettings.contentStartX
        var y = currentY + PdfPageSettings.SECTION_SPACING / 2
        
        // Section title
        canvas.drawText(
            title,
            rightX,
            y,
            PdfTypography.createSectionHeaderPaint()
        )
        y += 8f
        
        // Underline
        val textWidth = PdfTypography.createSectionHeaderPaint().measureText(title)
        canvas.drawLine(
            rightX - textWidth,
            y,
            rightX,
            y,
            thickLinePaint.apply { strokeWidth = 1.5f }
        )
        
        return y + 15f
    }
    
    /**
     * Render an info card (for account details, worker info, etc.)
     * 
     * @param canvas Canvas to draw on
     * @param title Card title
     * @param items List of label-value pairs
     * @param currentY Current Y position
     * @return Y position after card
     */
    fun renderInfoCard(
        canvas: Canvas,
        title: String,
        items: List<Pair<String, String>>,
        currentY: Float
    ): Float {
        val rightX = PdfPageSettings.contentStartX
        val leftX = PdfPageSettings.MARGIN_LEFT
        val cardWidth = PdfPageSettings.contentWidth
        val rowHeight = 22f
        val padding = PdfPageSettings.CARD_PADDING
        
        // Calculate card height
        val titleHeight = 30f
        val contentHeight = items.size * rowHeight
        val cardHeight = titleHeight + contentHeight + padding * 2
        
        var y = currentY + 10f
        
        // Card background
        val cardRect = RectF(
            leftX,
            y,
            leftX + cardWidth,
            y + cardHeight
        )
        canvas.drawRoundRect(
            cardRect,
            PdfPageSettings.CARD_CORNER_RADIUS,
            PdfPageSettings.CARD_CORNER_RADIUS,
            PdfTypography.createFillPaint(PdfColors.CardBackground)
        )
        
        // Card border
        canvas.drawRoundRect(
            cardRect,
            PdfPageSettings.CARD_CORNER_RADIUS,
            PdfPageSettings.CARD_CORNER_RADIUS,
            linePaint
        )
        
        // Card title
        y += padding + 15f
        canvas.drawText(
            title,
            rightX - padding,
            y,
            PdfTypography.createSubsectionHeaderPaint()
        )
        y += 20f
        
        // Separator under title
        canvas.drawLine(
            leftX + padding,
            y - 5f,
            rightX - padding,
            y - 5f,
            linePaint
        )
        y += 10f
        
        // Info items (2 columns)
        val labelPaint = PdfTypography.createInfoLabelPaint()
        val valuePaint = PdfTypography.createInfoValuePaint()
        val midX = leftX + cardWidth / 2
        
        items.forEachIndexed { index, (label, value) ->
            // Alternate between left and right columns
            if (index % 2 == 0) {
                // Right column (RTL)
                canvas.drawText("$label:", rightX - padding, y, labelPaint)
                canvas.drawText(value, rightX - padding - 80f, y, valuePaint.apply { textAlign = Paint.Align.RIGHT })
            } else {
                // Left column
                canvas.drawText("$label:", midX - 10f, y, labelPaint)
                canvas.drawText(value, midX - 90f, y, valuePaint.apply { textAlign = Paint.Align.RIGHT })
                y += rowHeight
            }
        }
        
        // Handle odd number of items
        if (items.size % 2 != 0) {
            y += rowHeight
        }
        
        return y + padding + 5f
    }
    
    /**
     * Render summary cards (for P&L summary)
     * 
     * @param canvas Canvas to draw on
     * @param cards List of (title, value, isPositive) triples
     * @param currentY Current Y position
     * @return Y position after summary cards
     */
    fun renderSummaryCards(
        canvas: Canvas,
        cards: List<Triple<String, String, Boolean?>>,
        currentY: Float
    ): Float {
        val cardWidth = PdfPageSettings.summaryCardWidth
        val cardHeight = PdfPageSettings.SUMMARY_CARD_HEIGHT
        val spacing = PdfPageSettings.ELEMENT_SPACING
        val leftX = PdfPageSettings.MARGIN_LEFT
        
        var y = currentY + 15f
        
        cards.forEachIndexed { index, (title, value, isPositive) ->
            val cardX = leftX + index * (cardWidth + spacing)
            
            // Determine card color based on type
            val backgroundColor = when (isPositive) {
                true -> PdfColors.SuccessLight
                false -> PdfColors.ErrorLight
                null -> PdfColors.InfoLight
            }
            val valueColor = when (isPositive) {
                true -> PdfColors.Success
                false -> PdfColors.Error
                null -> PdfColors.Primary
            }
            
            // Card background
            val cardRect = RectF(cardX, y, cardX + cardWidth, y + cardHeight)
            canvas.drawRoundRect(
                cardRect,
                PdfPageSettings.CARD_CORNER_RADIUS,
                PdfPageSettings.CARD_CORNER_RADIUS,
                PdfTypography.createFillPaint(backgroundColor)
            )
            
            // Card border
            canvas.drawRoundRect(
                cardRect,
                PdfPageSettings.CARD_CORNER_RADIUS,
                PdfPageSettings.CARD_CORNER_RADIUS,
                linePaint
            )
            
            // Title (centered)
            val titlePaint = PdfTypography.createTableBodyCenterPaint().apply {
                color = PdfColors.TextSecondary
            }
            canvas.drawText(
                title,
                cardX + cardWidth / 2,
                y + 25f,
                titlePaint
            )
            
            // Value (centered, larger)
            val valuePaintCard = PdfTypography.createTotalPaint().apply {
                color = valueColor
                textAlign = Paint.Align.CENTER
            }
            canvas.drawText(
                value,
                cardX + cardWidth / 2,
                y + 55f,
                valuePaintCard
            )
        }
        
        return y + cardHeight + 20f
    }
    
    /**
     * Render a highlight box (for net profit/loss)
     * 
     * @param canvas Canvas to draw on
     * @param title Box title
     * @param value Main value to display
     * @param subtitle Optional subtitle
     * @param isPositive True for success color, false for error color
     * @param currentY Current Y position
     * @return Y position after box
     */
    fun renderHighlightBox(
        canvas: Canvas,
        title: String,
        value: String,
        subtitle: String? = null,
        isPositive: Boolean,
        currentY: Float
    ): Float {
        val leftX = PdfPageSettings.MARGIN_LEFT
        val width = PdfPageSettings.contentWidth
        val height = 70f
        
        var y = currentY + 15f
        
        val backgroundColor = if (isPositive) PdfColors.SuccessLight else PdfColors.ErrorLight
        val borderColor = if (isPositive) PdfColors.Success else PdfColors.Error
        val valueColor = if (isPositive) PdfColors.Success else PdfColors.Error
        
        // Box background
        val boxRect = RectF(leftX, y, leftX + width, y + height)
        canvas.drawRoundRect(
            boxRect,
            PdfPageSettings.CARD_CORNER_RADIUS,
            PdfPageSettings.CARD_CORNER_RADIUS,
            PdfTypography.createFillPaint(backgroundColor)
        )
        
        // Box border (thicker)
        canvas.drawRoundRect(
            boxRect,
            PdfPageSettings.CARD_CORNER_RADIUS,
            PdfPageSettings.CARD_CORNER_RADIUS,
            Paint(Paint.ANTI_ALIAS_FLAG).apply {
                color = borderColor
                style = Paint.Style.STROKE
                strokeWidth = 2f
            }
        )
        
        val centerX = leftX + width / 2
        
        // Title
        canvas.drawText(
            title,
            centerX,
            y + 22f,
            PdfTypography.createTableBodyCenterPaint().apply {
                color = PdfColors.TextSecondary
                typeface = android.graphics.Typeface.DEFAULT_BOLD
            }
        )
        
        // Value
        canvas.drawText(
            value,
            centerX,
            y + 48f,
            PdfTypography.createGrandTotalPaint().apply {
                color = valueColor
                textAlign = Paint.Align.CENTER
            }
        )
        
        // Subtitle (if provided)
        if (subtitle != null) {
            canvas.drawText(
                subtitle,
                centerX,
                y + 62f,
                PdfTypography.createCaptionPaint().apply {
                    textAlign = Paint.Align.CENTER
                    color = valueColor
                }
            )
        }
        
        return y + height + 15f
    }
}
